### PR TITLE
Update indexpage.php

### PR DESCRIPTION
**Pull request by By-oussef**
Add Google Analitycs

### CODE REVIEW

**Comment by sbillard** [comment]
So, it seems you are adding the same code to various scripts. The proper way to do this is to create a plugin that inserts the code and register it to the themehead filter.

Please withdraw this pull request and #26 and prepare a plugin that does this code. (If needed you can limit the pages it loads the code on in the plugin.) Also in your pull request remove the code from the mobile theme as the  plugin will handle it.

**Comment by sbillard** [comment]
YOu can use the themeSwitcher as an example of how to do this. Look at its theme_head handling.

**Comment by By-oussef** [comment]
UA-109862535-3

**Comment by By-oussef** [comment]
THank you

**Comment by sbillard** [comment]
I have actually implemented and deployed this plugin in the current website. See bf18d196b9a669055d97f540d71feb368f56068e.

With the country effectively shut down, I had time to address it.

**Comment by By-oussef** [comment]
THank you Stephen

**Pull request closed without merging**
