### PR TITLE
Improve seo of npg site by google analitycs

### PR DESCRIPTION
**Pull request by By-oussef**
Improve seo of npg site by google analitycs for phpbb forum in search engines : google, bing, yandex, duckduckgo...

### CODE REVIEW

**Comment by sbillard** [comment]
You can't be serious. If it is necessary to modify all the files in this plugin then the plugin is worthless.

I especially think that having to modify the release notes is unlikely.

Please do not make extra work for others by not doing your homework.

**Comment by By-oussef** [comment]
Sorry Stephen,
No Stephen it is not the same plugin that you download Google Analitycs on phpbb. 
This one is another extension which is called: analitycseo the objective is to improve the seo of npg site. have several visitors because the site will be better referenced in the search engine.

Thank You

**Comment by sbillard** [comment]
Not listed on th ePHPBBS site.

**Comment by By-oussef** [comment]
Indeed Stephen you are right. I just checked it is a private plugin which is not put on the phpbb platform. I found an alternative to add the analitycs code on the forum and follow the performance of the pages to improve the seo is ads.

It is on phpbb we can add the google code analitycs.

**Comment by sbillard** [comment]
phpbb/googleanalytics is already added. The link you provide is for Advertisement Management. Not sure how that is applicable.

**Comment by By-oussef** [comment]
Yes the extension is called like that but we can add js css code ...
The google analitycs code can be added without any problem.

**Pull request closed without merging**
