### PR TITLE
Add Google Webmaster tools

### PR DESCRIPTION
**Pull request by By-oussef**
Add Google webmaster tools for to send all pages to search engine.

### CODE REVIEW

**Comment by By-oussef** [comment]
Hello Stephen
Thank you for your reply. this draw concerns the addition of Netphotograĥics to the search console. I want to send all the NPG pages to google so that the search engine finds all the pages and indexes the content of the site. The users can more easily find the site.
Thank you

**Comment by sbillard** [comment]
This change appears to add one file that is a single line. You should add to your description how this accomplishes "adding Google Webmaster Tools."

In general, when you make a ticket or propose a change you should provide as much detail as you can on what the change is, what you expect it to accomplish, and how the change accomplishes it. Otherwise it is simply not possible to assess the value or appropriateness of the change.

It would also be a good idea to explain how to use the feature so someone other than you could take it over if needed. All these points should be in the original commit message so that they track with the change in the GitHub repository.

**Comment by By-oussef** [comment]
Okay Stephen, I got it. Next time I will detail

**Comment by sbillard** [comment]
Ok, I will reject this pull request and await one that has the proper information.

**Pull request closed without merging**
