### PR TITLE
Improve indexing of netphotographics in google

### PR DESCRIPTION
**Pull request by By-oussef**
The purpose of this file :+1: 

Allow Google to access all of the pages in order to index them in its directory.

The purpose of this file is to improve SEO of NPG website in search engines.

https://github.com/netPhotoGraphics/Website/issues/12

### CODE REVIEW

**Comment by By-oussef** [comment]
+1

**Comment by By-oussef** [comment]
Why this file name: it is the Google webmaster tools that generate this file name, it is not me who decides.

Why put this file but it is to allow Google Bot to access netphotographics and crawl the whole site. Indexer all pages of the site.

I created a Google webmaster tools account to have this file.

**Comment by sbillard** [comment]
How does one access the account?

**Comment by sbillard** [comment]
One further question. Where should this file go? I am sure it will do no good being in the theme folder as Web browsers have no access to that folder.

**Comment by By-oussef** [comment]
Hello Stephen,
Thank you for your reply. This file must be at the root of the www / website for google to find it.
Thank You

**Comment by sbillard** [comment]
The repository is now updated to reflect this and the file uploaded to the site.

**Pull request merged**
